version: '3.8'
services:
  dynamodb-local:
    image:  "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    hostname: dynamodb
    restart: always
    volumes:
      -  /opt/dynamodb_data:/home/dynamodblocal/data
    ports:
      - "10000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal