
# Generated automatically from pi-hole script
version: "3.7"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    ports:
      # dns ports
      - "53:53/tcp"
      - "53:53/udp"
      # ftl (dhcp) ports
      #- "67:67/udp"
      #- "547:547/udp"
      # ports for http interface
      - "19080:80/tcp"
      - "19443:443/tcp"
    environment:
      TZ: Europe/Athens
      WEBPASSWORD: astrongpassword
    # Volumes store your data between container upgrades
    volumes:
      - "/usr/pihole/etc-pihole:/etc/pihole"
      - "/usr/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/"
      - "/usr/pihole/etc-resolv.conf:/etc/resolv.conf"
      - "/usr/pihole/pihole.log:/var/log/pihole.log"
    dns:
    # IP of your DNS entries
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

