version: "3.2"

services:
  # get the postgres image and make it a service
  db:
    image: timescale/timescaledb:latest-pg12
    restart: always
    environment:
      # you should probably change this
      POSTGRES_PASSWORD: mysecretcombination
    ports:
    - "5432:5432"